### ISSUE TITLE
Cosmos Keys

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [Azure-Samples/ARGUS#5]
Dear all,

Thank you for the project, I am not able to set the correct vars for

```
COSMOs_URL
COSMOS_KEY
```
I am looking here, normally I compose the connection string and use the normal mongodb client. When I try to set the host as `https:// bla bla` and using the key from the UI I got an error

```
ServiceResponseError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

<img width="262" alt="Screenshot 2024-08-08 at 12 06 33" src="https://github.com/user-attachments/assets/b44e8995-fc3c-419f-8f7c-38b8135f92db">

Would you be able to help?

Thanks a lot,

Francesco Zuppichini

**Comment by albertaga27** [comment]
Hi, please use a cosmosdb nosql instance instead of the mongodb one

**Comment by FrancescoSaverioZuppichini** [comment]
@albertaga27 thank, then how do I set it up? I need a partition key

<img width="453" alt="Screenshot 2024-08-19 at 09 21 25" src="https://github.com/user-attachments/assets/e21f0f38-e7eb-41b5-a048-dbde470b1130">

Otherwise the app doesn't work, I guess it needs the db to be created before hand

<img width="1335" alt="Screenshot 2024-08-19 at 09 22 07" src="https://github.com/user-attachments/assets/259989a0-0f4c-4156-8897-dd13d56d81e9">

Thanks a lot!

**Comment by albertaga27** [comment]
Please follow the instructions in the README: the one-click deployment takes care of creating and configuring all the resources including cosmos. If you want to test locally or do manual deployment you need to create the resources first then use docker images in the docker folder to spin everything up. The solution automatically creates the DB and the containers if not existing at first utilization.

**Comment by FrancescoSaverioZuppichini** [comment]
I can’t one click deploy it, it has to follow some internal rules and I can’t just run it like that.

Can you help out? Otherwise I’ll just report that I am not able to run it and code something different from scratch

Francesco Saverio Zuppichini
Mobile: +41 76393​6765
Via Monte Boglia 17/a
6900, Lugano

**Comment by albertaga27** [comment]
Solved with private networks and vpn configurations

**Comment by albertaga27** [comment]
closing

**Comment by albertaga27** [comment]
closing
